version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/teamproject
    environment:
      PYTHONUNBUFFERED: 1
      PYTHONPATH: /app
    command: ["python", "app/main.py"]